/** ui */
const ui = {
  SET_LOADING: 'SET_LOADING',
};

/** bus */
const bus = {
  SET_CITY: 'SET_CITY',
  SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',
  SET_ROUTES_STOPS: 'SET_ROUTES_STOPS',
  SET_CURRENT_ROUTE_STOPS: 'SET_CURRENT_ROUTE_STOPS',
  UPDATE_STOP_STATUS: 'UPDATE_STOP_STATUS',
};

export {
  ui, bus,
};
